---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 6.8.3 # set to empty to build with most recent version of gradle
      gradle_commands: build # default is build
      artifact_dir: build/distributions/*
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }} and Gradle 
        uses: ome/action-gradle@v3.2
        with:
          java-version: ${{ matrix.java }}
          gradle-version: ${{ env.gradle_version }}
      - name: Run commands
        run: gradle ${{ env.gradle_commands }}
      - name: Upload artifacts
        if: startsWith(matrix.os, 'ubuntu') && matrix.java == '8'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.artifact_dir }}
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    env:
      publishing_target: github # default is github
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ env.publishing_target }} == 'github'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
